ocsigen/tyxml

lib/svg_f.ml
lib/svg_sigs.mli

I tried to keep the same conventions already used in Tyxml.  I just wasn't sure about `linethrough`: should it be `lineThrough` or `line_through` instead?

Add constructor functions for missing text attributes

---

lib/html5_f.ml
lib/html5_f.mli
lib/html5_sigs.mli
lib/svg_f.ml

This PR follows from a suggestion by @Drup in an [jsoo issue](ocsigen/js_of_ocaml#276).
Description:
Use [Svg.svg] to create an svg embedded in a [Html5.elt] instead of [Xml.node].

Fix svg element creation in Html5

---

lib/svg_f.ml
lib/svg_sigs.mli
lib/svg_types.mli
syntax/pa_tyxml.ml

Both `alignment-baseline` and `dominant-baseline` are part of the SVG 1.1 standard:
http://www.w3.org/TR/SVG11/text.html#AlignmentBaselineProperty
http://www.w3.org/TR/SVG11/text.html#DominantBaselineProperty
The `text` element is clearly also part of the standard, and it does accept the `class` attribute:
http://www.w3.org/TR/SVG11/text.html#TextElement

Allowing SVG attributes: class in text; {alignment,dominant}-baseline

---

lib/html5_f.ml
lib/html5_f.mli
lib/html5_sigs.mli
lib/svg_f.ml
lib/svg_f.mli
lib/svg_sigs.mli
lib/xml.ml
lib/xml.mli
lib/xml_sigs.mli
lib/xml_wrap.ml
lib/xml_wrap.mli

This removes all the wrapped functor, simplify most signatures and remove the need for two arguments to use `Html5` signature (see [this](https://github.com/Drup/ocaml-markdown/commit/aab07fa115e2a72e78db09bfc7e50f8228ac678f)). 
This is done by adding a `W` module to `Xml` everywhere so that, given an `Xml` module (and, by extension, an `Html5` or `Svg` modules containing one, and all of them should), you can use the basic operations on the wrapped element.
The `'a wrap` and `'a list_wrap` are now just aliases. 
It also normalize the naming scheme. Every signatures (`Xml`, `Xml_wrap`, `Svg`, `Html5`) comes in two versions, the `T` version, which is the normal, fully general one and the `NoWrap` version, which comes with the forced equality `Xml.W = Xml_wrap.NoWrap`. 
It's breaking for …

Rework wrapping

---

doc/manual-wiki/functors.wiki
lib/html5_f.ml
lib/html5_f.mli
lib/html5_sigs.mli
lib/html5_types.mli
lib/svg_f.ml
lib/svg_f.mli
lib/svg_sigs.mli
lib/svg_types.mli
lib/xml_wrap.ml
lib/xml_wrap.mli

The `sharedreactcontent` branch provides the changes that we need in order to implement an `R` module for Eliom shared values.
The main points are:
* `Xml_wrap.T'` adds a type constructor `ft` to `Xml_wrap.T`. This is in order to accommodate
shared functions for operating on shared values.
* A signature `Conv` contains instances of `ft` for all operations on wrapped elements that the
functor performs. This is needed because we cannot simply inject server-side functions.
* Our use of shadow types becomes "customizable". The functor receives types `u` and `'a s` related
by operations `shadow : u -> 'a s` and `unshadow : 'a s -> u` . `'a s` becomes the type of the resulting
HTML elements. This is in order to achieve type equalities between different functor invocations (in
Eliom) that would …

Functorial interface updated to support shared reactive Eliom

---

lib/html5_f.ml
lib/svg_f.ml

Luckily, svg, html5 and javascript's norms seem to agree on how numbers should be printed!
Our unit printing is slightly mess, we should clean that up at some point ...
cc @mfp

Use Xml_print.string_of_number to print floats.

---

lib/html5_f.ml
lib/html5_sigs.mli
lib/html5_types.mli

Hi,
This is a patch proposal to add the `<main>` tag. I am really not sure if the `core_flow5` type is the best place for this tag. The HTML5 spec specifies two restrictions: `<main>` must not be a descendent of an `<article>`, `<aside>`, `<footer>`, `<header>`, or `<nav>` element and authors must not include more than one `<main>` element in a document. But the living HTML standard removes these two restrictions.
ref. :  https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main and https://html.spec.whatwg.org/multipage/semantics.html#the-main-element

Add <main> tag

---

lib/html5_f.ml

This is not a long-term solution, because it exploits the accidental type equality between URIs and strings. It suffices to keep Eliom et al. happy for now.

Work around issue #81

---

lib/html5_f.ml
lib/html5_sigs.mli
lib/html5_types.mli

https://www.w3.org/html/wg/drafts/html/master/semantics.html#attr-img-sizes
https://www.smashingmagazine.com/2014/05/responsive-images-done-right-guide-picture-srcset/
As this attribute can be quite complex (for instance: `(min-width: 36em) calc(.333 * (100vw - 12em)), 100vw`), a string list seems a good realistic choice.

Add sizes attribute in <img> tag

---

lib/html5_f.ml
lib/html5_sigs.mli
lib/html5_types.mli
lib/svg_f.ml
lib/svg_sigs.mli

Per #72.
This doesn't block the ppx – I have `a_sandbox` special-cased for the time being.

Fix inconsistent naming and typos.

---

lib/html5_sigs.mli
lib/svg_sigs.mli

Fix this test case:
```
module Tyxml_backend : Html5_sigs.NoWrap
= struct
include Html5.M
module Svg = Svg.M
end
```

Fix constraints on W.ft in the functorial interface.

---

lib/html5_f.ml
lib/html5_sigs.mli
lib/html5_types.mli
lib/svg_f.ml
lib/svg_sigs.mli
lib/svg_types.mli

This is consistent with how `Html5_sigs.T.a_step` is represented, and makes the ppx ever-so-slightly less tedious to program. Curious to hear about the impact on users.
**Edit**: also replacing type of `a_sizes`. I suppose we could also go the other way, keep these as they are, but change `a_step` to a variant.

Replace some option-like variants by options.

---

_oasis
ppx/ppx_tyxml_empty.ml

Workaround https://github.com/ocsigen/lwt/issues/91

Makes the ppx archive non empty.

---

_oasis
lib/xml_print.ml
test/test_html.ml

See https://github.com/ocsigen/tyxml/issues/90
This is only a simplistic fix (and it adds re as a dep of the functor part, which is annoying).

Do not escape comments

---

_oasis
_tags
examples/mini_website_ppx/.merlin
examples/mini_website_ppx/Makefile
examples/mini_website_ppx/Readme.md
examples/mini_website_ppx/minihtml.ml
implem/html5.mli
implem/svg.mli
ppx/ppx_attribute_value.ml
ppx/ppx_attribute_value.mli
ppx/ppx_attributes.mli
ppx/ppx_common.ml
ppx/ppx_common.mli
ppx/ppx_element.ml
ppx/ppx_element.mli
ppx/ppx_element_content.ml
ppx/ppx_element_content.mli
ppx/ppx_tyxml.ml
ppx/ppx_tyxml.mli
test/.merlin
test/test_ppx.ml

I removed the tyxml quotation. The namespace is now always provided by the quotation.
- Antiquotations inside lists (that is, star elements) now should be lists.
Antiquotations inside unary elements can still be single elements
- The ppx will return a single element if there is only one element in the quotation.
- pcdata and svg-inside-html handling is probably a bit better now.
- Some judiciously placed type constraint allow better type errors for quotations.
@aantron: I think I broke `adjust_location` in one of my patches ...

Various improvements to the ppx:

---

ppx/ppx_element_content.ml
test/test_ppx.ml

Resolves #119.
In the original PR, `pcdata` calls were unqualified at the time whitespace was filtered in `<html>` elements. This has since changed. This commit changes the pattern to tolerate modules prefixed to `pcdata`.

Restore whitespace filtering in <html>.

---

lib/svg_f.ml
lib/svg_f.mli
lib/svg_sigs.mli

Make Svg wrapped function API similar to Html.

---

_oasis
_tags
examples/basic_website_ppx/.merlin
examples/basic_website_ppx/Makefile
examples/basic_website_ppx/Readme.md
examples/basic_website_ppx/home.css
examples/basic_website_ppx/main.js
examples/basic_website_ppx/site_html.ml
examples/mini_website_ppx/minihtml.ml
lib/html_sigs.mli
ppx/ppx_element_content.ml
ppx/ppx_element_content.mli
ppx/ppx_tyxml.ml
test/test_ppx.ml

While adding the ppx examples, I noticed several bugs.
The biggest change is that surrounding whitespaces in a quotation are removed. However, it is not removed when there are other pcdata elements. The test cases show it quite well. I'm not sure how I feel about this behavior.
I also added whitespace filtering for head, ul and ol elements.

Add ppx examples and fix various associated bugs

---

lib/svg_sigs.mli

Stroke, fill, gradient stop color, `<foreignObject>`, and `<metadata>` are not events :)

Move some SVG values to the proper sections

---

lib/html_f.ml
lib/html_types.mli

Without this change, the PPX generates `` `Raw_mediadesc "tv"`` for `media=tv`, and similarly for `media=tty`.
Another way to solve this is to do a case-insensitive search for a matching variand. That slightly decreases the consistency of the API, but would allow intuitive labels `` `TV`` and `` `TTY`` to work "correctly" with the PPX. Let me know if you prefer that.

Fix capitalization in Html5_types.mediadesc_token

---

lib/html_f.ml
lib/html_types.mli
test/test_ppx.ml

This kind of `<link>` element is common in SEO work.

Add "canonical" link type

---

doc/manual-wiki/ppx.wiki
examples/mini_website_ppx/minihtml.ml
myocamlbuild.ml
ppx/ppx_tyxml.ml
test/test_ppx.ml

This works with functions and multiple bindings. In particular, something like that works:
```ocaml
let%html make_content content = {|
<div class="content">|} content {|</div>
|}
let%html rec f = function
| [] -> ""
| h :: t -> "<li>" [h] "</li>" (f t)
val f :
[< Html_types.li_content_fun ] Tyxml_html.elt list ->
[> Html_types.li ] Tyxml_html.elt list
```
(And now that I've written out the second example, I'm not sure it's a great idea anymore :D)

Implement let%html constructs

---

lib/html_sigs.mli
ppx/ppx_attribute_value.mli

This attribute is deprecated in HTML5, and was reportedly not well-supported by browsers before that.
It could be marked deprecated instead, but it seems the argument for removing it entirely is stronger than even for `cellspacing`/`cellpadding`.

Remove "char" attribute

---

lib/html_sigs.mli
test/test_ppx.ml

a_mime_type is usable in `<object>`, `<embed>`, `<area>`, and `<link>` elements, where it corresponds to the HTML attribute "type".

Element and attribute reflection fixes

---

lib/html_f.ml
lib/html_sigs.mli

Admittedly a nit, but it bugged me that the child list was named `child`.

Rename menu ?child to ?children

---

ppx/ppx_element.ml
ppx/ppx_tyxml.ml

- OCaml error messages are not punctuated.
- "Authorized" -> "supported."

Fix some error messages

---

lib/html_f.ml
lib/html_sigs.mli
lib/html_types.mli

Only `GET` and `POST` are officially supported.
W3C: https://www.w3.org/TR/html5/forms.html#attr-fs-method
WHATWG: https://html.spec.whatwg.org/multipage/forms.html#attr-fs-method
Perhaps there was some rationale for originally including `PUT` and `DELETE`?
The `dialog` value from the WHATWG version is for the `<dialog>` element, which is in HTML 5.1 right now, but it doesn't look well-supported at this point: http://caniuse.com/#feat=dialog. Do you want to include it?

Remove form methods PUT and DELETE

---

_oasis
myocamlbuild.ml
opam
ppx/ppx_attribute_value.ml
ppx/ppx_attributes.ml
ppx/ppx_attributes.mli
ppx/ppx_common.ml
ppx/ppx_common.mli
ppx/ppx_element_content.ml
ppx/ppx_tyxml.ml
setup.ml
test/html_fail.expected

We have lot's of deprecation warnings, but it's not possible to fix them
while still keeping 4.02 compatibility.

Restore compatibility with 4.03

---

ppx/ppx_tyxml.ml
ppx/ppx_tyxml.mli

Stolen from https://github.com/ocsigen/tyxml/pull/128, This one can be merged right now.

Make the Ppx_tyxml api a bit friendlier.

---

Contributing.md
README.md
doc/manual-wiki/intro.wiki
tools/autoname.ml

As requested.
Proofread the 3 files in the diff. Based on #152.
I think for really proper usage, you should capitalize PPX where it is not the name of an option (i.e. `-ppx`). The lowercase usage seems to have evolved from people dropping the `-` from `-ppx`. We have both in TyXML right now, e.g. change log has PPX, README has ppx.
Also, I think you should delete the "Ocaml libary to..." part of the tag line in GitHub :)

Documentation nit list.

---

.jenkins.sh
tyxml_ppx.opam

I also removed the Jenkins pin on the Markup.ml development branch, so this should be merged after https://github.com/ocaml/opam-repository/pull/6472 and the new `markup` is installable from OPAM. I'll bump this thread when that's so.

Require Markup.ml 0.7.2.

---

ppx/ppx_common.ml

Resolves #157. cc @eras
With this change, the output is (I reformatted the example slightly):
```
File "foo.ml", line 2, characters 20-21:
Error: head element must have exactly one title child element
```
The error itself may seem counterintuitive, but the spec says to silently insert `<head>` and `<body>` elements, then put `error` into the body. The PPX then requires `<head>` to have a title, but it doesn't. Perhaps we should address implicit elements in error message better in the future.

Flush error message formatter in the PPX.

---

.merlin
_oasis
lib/xml_print.ml
tyxml.opam

Do not merge before Uutf 1.0.0 is released (will happen soon) otherwise you'll need a a pin on `uutf`. Adds a dependency on the `uchar` compatibility package to the project.

Support for Uutf 1.0.0.

---

CHANGES
lib/html_f.ml
lib/html_sigs.mli
lib/html_types.mli

See https://www.w3.org/TR/html5/forms.html#attr-input-minlength
Fixes #169

Add support for the `minlength` form attribute

---

CHANGES
lib/html_f.ml
lib/html_sigs.mli
lib/html_types.mli
ppx/ppx_attributes.ml
ppx/ppx_reflect.ml
test/test_ppx.ml

See https://www.w3.org/TR/wai-aria-1.1/#states_and_properties
The specification indicates that many aria- attributes are only valid for
elements of a given "role" (as specified by the "role" attribute). Here, we do
not try to encode these invariants in tyxml types (it is considered not worth
the trouble). A single [a_aria] function is thus provided, with [a_aria "foo"]
corresponding to the "aria-foo" attribute.

Add basic support for aria-* attributes

---

CHANGES
lib/html_sigs.mli

This is the easy part of #182. All the types defined in Html_sigs.T that were exactly as defined in Html_types have been replaced by the corresponding type (defined in Html_types).
There remain two problems, that should be addressed in separate issues:
- The area element allows some Download attribute in Html_types, but not in Html_sigs.T;
- The object element allows some Object_interactive output in Html_types, but not in Html_sigs.T.
Hence, this closes #182.

Html sigs avoid variants

---

examples/basic_website/site_html.ml
examples/basic_website_ppx/site_html.ml
examples/mini_website/minihtml.ml
examples/mini_website_ppx/minihtml.ml
implem/tyxml_html.mli
implem/tyxml_svg.mli
implem/tyxml_xml.mli
lib/xml_print.ml
lib/xml_sigs.mli
test/emitbig.ml

The goal is not to have a great indentation engine, but something that is sufficient to be readable. There are many much more sophisticated pretty-printers for html out there. :)
Here is the output for the small website example:
```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head><title>Your Cool Web Page</title>
<link rel="stylesheet" href="home.css"/>
</head>
<body><div id="image_box"></div>
<div id="content_box">
<nav>
<ul class="links_bar" id="links_bar"><li id="home_click">My Musings</li>
<li id="about_click">About Me</li><li id="blog_posts_click">Blog</li>
<li id="hackathons_click">Hackathons</li>
</ul>
</nav><div id="payload"><div><h2>Hello Coder</h2></div></div>
<footer id="footer_box">
<p>This site was made with <a href="http://ocaml.org">OCaml</a> and 
<a …
```

Simplistic indentation for the Format-based printer.

---

lib/html_types.mli

From https://www.w3.org/TR/html5/grouping-content.html#the-dt-element:
> Content model:
Flow content, but with no header, footer, sectioning content, or heading content descendants.
By contrast, TyXML has:
https://github.com/ocsigen/tyxml/blob/820d3c6b3d795aec948314e026ec0c9484b54762/lib/html_types.mli#L1397
This isn't quite restrictive enough, because, e.g., a `div` could have a nested `h2`, but I am under the impression that is already an issue in TyXML.

Allow restricted flow content in dt elements

---

examples/mini_website_ppx/minihtml.ml
ppx/common.ml
ppx/common.mli
ppx/element_content.ml
ppx/tyxml_ppx.ml
test/test_ppx.ml

I was somehow convinced that this was working already, but apparenty it didn't.
I extended the test cases to cover wrapped APIs and I fixed a few bugs.
After this patch, this works:
```ocaml
open Tyxml_js.R
let%html make title content =
{|<html>
<head>
<title>|}title{|</title>
</head>
<body>|}content{|</body>
</html>
|}
```
and yields a completely reactive webpage. :heart: 
```ocaml
val make :
[< Html_types.title_content_fun ] Tyxml_js.To_dom.elt React.signal ->
[< Html_types.object__content_fun > `PCDATA ] Tyxml_js.To_dom.elt ReactiveData.RList.t ->
[> Html_types.html ] Tyxml_js.To_dom.elt
```

Make the ppx work with wrapped APIs.

---

docs/Makefile
lib/jbuild
tyxml.opam

This has been included in the OCaml standard library since
version 4.03.0, which is also the minimum version used by
tyxml.
Removing the compat eliminates a non-dune build dependency,
which in turn makes it easier to embed tyxml as part of a
larger monorepo build using a single dune invocation.
Signed-off-by: Anil Madhavapeddy <anil@recoil.org>

remove uchar compatability library from build

---

lib/html_sigs.mli
ppx/element_content.ml
ppx/element_content.mli
ppx/reflect/reflect.ml

It calls `filter_whitespace` on children just before passing them to the assembler. It avoids the need to write an explicit assembler.
In the 2nd commit I replaced the assembler for `ul`, `ol` and `select` with this annotation and used it on top of `head` and `html`.
I tried to implement it as generic as possible. Adding similar annotations should be very easy.

Add `[@@reflect.filter whitespace]` annotation

---

CHANGES.md
lib/html_types.mli

https://developer.mozilla.org/fr/docs/Web/HTML/Element/script
`a_crossorigin` happens to already be defined, with an already correct type. This PR merely adds this as an acceptable attribute for `script`.

Allow crossorigin attribute for script element

---

CHANGES.md
lib/html_f.ml
lib/html_sigs.mli
lib/html_types.mli
ppx/attribute_value.ml
ppx/attribute_value.mli
ppx/reflect/reflect.ml
test/test_ppx.ml

https://html.spec.whatwg.org/multipage/iframe-embed-object.html#the-iframe-element
https://html.spec.whatwg.org/multipage/iframe-embed-object.html#attr-iframe-referrerpolicy
Note that:
- Referrerpolicy is an enumerated attribute, usually translated as a variant, except is also accepts the empty string as a valid keyword. I added a `variant_or_empty` parser that can parse this kind of attribute, parameterised by the variant to which the empty string will be mapped (given as a string, for instance `"Empty"` for the ``Empty` polyvar).
- Some other elements such as `a` and `area` should accept referrer policies, but the MDN considers this as experimental. Although I did not add this support, this should not be too hard now that the attribute exists.
Thanks @Drup for the help.

Add `allowfullscreen`, `allowpaymentrequest`, `referrerpolicy` iframe attributes

---

lib/html_f.ml
lib/html_sigs.mli
lib/html_types.mli
test/test_html.ml

- [W3C](https://www.w3.org/TR/html5/semantics-scripting.html#the-template-element)
- [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template)

Add <template> tag

---

lib/html_sigs.mli
ppx/element_content.ml
test/test_ppx.ml

Whitespaces are treated as `PCDATA` which are not accepted in `table` and `tr` elements.
~~I took example on #121 but I suspect this is not the best approach as this problem may occur in a lot of other elements. Would adding some kind of `[@@reflect.filter_whitespace]` in `html_sigs.mli` a better solution ?~~
~~While adding a test, I could not write `[table [tbody [tr [td [txt "foo"]] ; tr [td [txt "bar"]]]]]`. `table` does not accept `tbody`.~~
~~I tried doing the same for `colgroup`, `thead` and `tfoot` elements (see https://github.com/Julow/tyxml/compare/whitespace_in_tr...whitespace_in_table_full) but I had a similar problem.~~
Use the annotation added in https://github.com/ocsigen/tyxml/pull/226

Whitespace in table

---

examples/basic_website_jsx/home_page.re
examples/basic_website_jsx/site_html.re
jsx/tyxml_jsx.ml

Homemade elements are distinguished by paths whose last part starts with an uppercase. Those will be preserved with the following spec:
- `<Foo a=x> children </Foo>` turns into `Foo.createElement ~a:x ~children:children ()`
- `<Foo a=x />` turns into `Foo.createElement ~a:x ()`
No children at all.
Apparently, this is consistent with revery (cc @wokalski)
The list of children are interpreted according to the usual tyxml JSX rule and will be wrapped. In particular, if the tyxml is reactive, it'll be a reactive list.
@Khady, does that work for you ? :)
The previous version removed the `()` at the end, but keeping only labelled argument is a recipe for trouble, and @wokalski gave a fairly convincing case for removing the `~children` argument when the list is empty.

Preserve homemade elements.

---

lib/html_f.ml
lib/html_sigs.mli
lib/html_types.mli
syntax/element_content.ml
syntax/element_content.mli
test/test_html.ml
test/test_ppx.ml

- [HTML Living standard](https://html.spec.whatwg.org/multipage/embedded-content.html#the-picture-element)
- [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture)

Add <picture> tag

---

lib/html_f.ml
lib/html_sigs.mli
lib/html_types.mli

Based on https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode.
Fixes #278.

Update allowed inputmodes.

---

.github/workflows/workflow.yml
docs/Makefile
dune-project
jsx/dune
jsx/tyxml_jsx.ml
ppx/dune
ppx/register/dune
ppx/register/tyxml_ppx_register.ml
ppx/tyxml_ppx.ml
ppx/tyxml_ppx.mli
syntax/attribute_value.ml
syntax/attribute_value.mli
syntax/attributes.ml
syntax/attributes.mli
syntax/common.ml
syntax/common.mli
syntax/dune
syntax/element.mli
syntax/element_content.ml
syntax/element_content.mli
syntax/reflect/dune
syntax/reflect/reflect.ml
test/dune
test/ppx.ml
test/test_ppx.ml
tyxml-jsx.opam
tyxml-ppx.opam
tyxml-syntax.opam

Before, the 2 ppx rewriters `tyxml-ppx` and `tyxml-jsx` as well as the internal `.ml`-file generator in /syntax/ were based on `omp`: the former two on the `omp` driver and all of them on `Ast_408`. None of those will exist in `omp 2.0.0` anymore. For more information on that `omp` change, see https://discuss.ocaml.org/t/ocaml-migrate-parsetree-2-0-0/5991 by @jeremiedimino.
This PR ports those 3 ppx's from the direct use of `omp` and tools like `ppx_tools_versioned` to `ppxlib`. It also adds a couple of small additions to the `tyxml-ppx`-tests. With this change, compiler-versions >= 4.04 are supported; before it was >= 4.02.
Closes https://github.com/ocaml-ppx/ppxlib/issues/146.
@NathanReb , would you mind having a look at this?

Port the 3 ppx's to `ppxlib`

---

.github/workflows/workflow.yml

With the introduction of ppxlib, now we support up to OCaml 4.12.

Add 4.11.x and 4.12.x to GitHub Actions workflow

---

lib/html_f.ml
test/test_html.ml

According to :  
- [HTML Specs](https://html.spec.whatwg.org/multipage/embedded-content.html#the-picture-element)

[picture-tag] <img> should be the last child of a <picture> tag

---

lib/html_types.mli
test/test_html.ml

"The value of this attribute is ignored when the <source> element is
placed inside a \<picture\> element." According to : [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Source)

[source-tag] we should allow srcset attribute in source tags

---

CHANGES.md
lib/svg_f.ml
lib/svg_sigs.mli
lib/svg_types.mli
syntax/attribute_value.ml
syntax/attribute_value.mli
test/test_jsx.re
test/test_ppx.ml

Hello!
I noticed that there is a `` `Fill_rule`` constructor in `Svg_types.presentation_attr`, but I could not find an attribute function that uses it. So, this PR adds an `a_fill_rule` attribute function that accepts `` `Nonzero `` or `` `Evenodd ``.
See https://www.w3.org/TR/SVG11/painting.html#FillRuleProperty for details on the fill-rule attribute.
I believe this branch is at least mostly ready for review. Since this is my first contribution, I'm not entirely sure. I have succeeded in using `a_fill_rule` from my local fork in another project, and the existing unit tests are passing, but I have not added any new unit tests.

Add svg fill-rule attribute

---

lib/html_sigs.mli
syntax/element_content.ml
syntax/element_content.mli
test/test_ppx.ml

The solution relies on previous work for empty `<script>` tags.

ppx: textarea tag should be allowed to have no child 

---

dune-project
jsx/tyxml_jsx.ml
ppx/tyxml_ppx.ml
syntax/name_convention.ml
tyxml-syntax.opam
tyxml.opam

fix build with OCaml 5 (drops support for 4.02)

---

lib/html_f.ml
lib/html_sigs.mli
lib/html_types.mli
test/test_html.ml

- First commit: corrects a subtle typo `Formation` -> `Formaction` in the `input_attrib`.
- Second commit: Even though `formmethod` is deprecated, the W3C specification of `<input>` does not accept a `method` attribute but rather `formmethod`
https://www.w3.org/TR/2011/WD-html5-20110525/the-input-element.html
I've kept the `method` attribute for `button` and `input` for backwards compatibility, but in an ideal world it would be removed.

Reintroduction of `formmethod`

---

lib/svg_sigs.mli
test/test_svg.ml

It should fix #313.
I'm surprised that I didn't had to change any implementation, but just the signature. Maybe we should add some tests.

Typo in polymorphic variant `Gradient_Transform`.

---

CHANGES.md
lib/svg_f.ml
lib/svg_sigs.mli
test/test_svg.ml

I was in need of this attribute.
Note that `clip-path` SVG presentation attribute is different from the `clipPath` SVG tag, which is already supported by TyXML.

Adding support for the clip-path presentation attribute.

---

.github/workflows/workflow.yml
dune-project
ppx/tyxml_ppx.ml
tyxml-jsx.opam
tyxml-ppx.opam
tyxml-syntax.opam
tyxml.opam

This PR is a patch for an upcoming release of ppxlib where the internal AST is [bumped from 4.14 to 5.2](https://github.com/ocaml-ppx/ppxlib/pull/514). Until that is merged and released, there is no reason to merge this PR.
To test these changes, you can use the following opam-based workflow. I've made releases of most of these patches to an opam-repository overlay.
```shell
opam switch create ppxlib-bump --repos=ppxlib=git+https://github.com/patricoferris/opam-repository#5.2-ast-bump
opam install <your-package>
```
The following describes the most notable changes to the AST.
Note: no update has been made of the `opam` file, but `ppxlib` will likely need a lower-bound before merging/releasing.
---
In the parsetree currently, functions like:
```ocaml
fun x y z -> ...
```
Are represented …

Prepare for 5.2 AST bump
