lib/html5_f.ml, lib/html5_sigs.mli, lib/html5_types.mli
https://www.w3.org/html/wg/drafts/html/master/semantics.html#attr-img-srcset
See also for instance: 
https://developer.mozilla.org/en-US/Learn/HTML/Howto/Add_responsive_image_to_a_webpage
https://bocoup.com/weblog/smaller-faster-websites
https://www.smashingmagazine.com/2014/05/responsive-images-done-right-guide-picture-srcset/
=> Add srcset attribute in <img>

lib/html5_f.ml, lib/html5_sigs.mli, lib/html5_types.mli
I think I'm going to wait before merging this one for the next major version of tyxml (along with some other breaking changes) in order not to break compat in each minor version of tyxml...
=> Various simplification in trivial attributes.

examples/basic_website/.merlin, examples/basic_website/Makefile, examples/basic_website/home.css, examples/basic_website/main.js, examples/basic_website/site_html.ml
=> Add basic, statically generated website example

.gitignore, .jenkins.sh, _oasis, myocamlbuild.ml, opam, tests/.merlin, tests/html_fail.expected, tests/html_fail.top.ml, tests/test_html.ml
The build system part is quite repugnant, but surprisingly, it seems to work.
@gasche: I had trouble to create a rule that doesn't produce anything. Is this use of stamp correct ?
Also, if anyone has a better solution to avoid all the load/requires at the top of the files (and better integrate with oasis), that would be nice.
We only need to add tests now ...
=> Add testing infrastructure.

.merlin, _oasis, lib/xml.ml, myocamlbuild.ml, opam, tests/html_fail.top.ml, tests/test_html.ml
This job technically doesn't need a regex engine, but it's the quickest way.
=> Avoid usage of str.

_oasis, implem/top/.merlin, implem/top/tyxml_top.ml
```ocaml
- : [> Html5_types.p ] Html5.elt = <p></p>
```
=> Toplevel printers are awesome

.jenkins.sh, _oasis, myocamlbuild.ml, opam, ppx/ppx_tyxml.ml, ppx/ppx_tyxml.mli, ppx/ppx_tyxml_ex.ml
The ppx's packaging was buggy, It was dragging various dependencies (it was most annoying in the toplevel).
=> Improve packaging

implem/html5.mli, implem/svg.mli, lib/xml_print.mli, lib/xml_sigs.mli
=> Use asprintf instead of sprintf in documentation.

doc/indexdoc, doc/manual-wiki/intro.wiki, doc/manual-wiki/menu.wiki, doc/manual-wiki/ppx.wiki, ppx/ppx_tyxml.mli
I decided not to change the tutorial much because I think there are enough to understand about the type system (which is the main subject of the tutorial) and it would not be beneficial to present the syntax too.
=> Documentation for the ppx.

lib/html5_f.ml, lib/html5_sigs.mli, lib/html5_types.mli, lib/svg_sigs.mli, ppx/ppx_attribute_value.ml, ppx/ppx_attribute_value.mli, ppx/ppx_reflect.ml
=> Remove cellspacing, cellpadding, charoff.

lib/html5_f.ml, lib/html5_sigs.mli, lib/html5_types.mli
See https://github.com/ocsigen/tyxml/issues/72
=> Html attribute cleanup.

lib/html_f.ml, lib/html_sigs.mli, ppx/ppx_attribute_value.ml, ppx/ppx_attribute_value.mli, ppx/ppx_reflect.ml, test/test_ppx.ml
This also improves handling of boolean (and unit) attributes in the ppx. It also fixes on/off attributes.
=> Add unit arg for constant attributes.

ppx/ppx_element_content.ml, test/test_ppx.ml
=> Antiquotations are not whitespace.

.jenkins.sh
=> Pin to development Markup.ml in Jenkins

ppx/ppx_tyxml.ml
This should fix locations. See the comment in the diff for an overview of the approach. Basically, this does a "dry run" pass through the input stream, in which Markup.ml decodes and assigns locations to characters (and normalizes newlines), but does not parse further. The pass logs these locations at the beginning of each string in the quotation, and uses that to map Markup.ml locations to OCaml.
This will only work with the `input-stream` branch of Markup.ml. If we keep this approach, then I will merge that into `master`.
I chose to hardcode the encoding to UTF-8 again, because the dry run doesn't try to infer the encoding.
=> Fix location handling in the PPX

lib/html_f.ml, lib/html_sigs.mli, lib/html_types.mli, ppx/ppx_attribute_value.ml, ppx/ppx_attribute_value.mli, ppx/ppx_reflect.ml, test/test_ppx.ml
https://github.com/ocsigen/tyxml/pull/145 rebased.
=> Support date-time

CHANGES, lib/html_f.ml, lib/html_sigs.mli, lib/html_types.mli, ppx/ppx_reflect.ml
See https://www.w3.org/TR/role-attribute/ and also https://www.w3.org/TR/wai-aria/
Fixes #165
=> Add support for the `role` attribute.

_oasis, setup.ml
=> Expose Ppx_common, which appears in Ppx_tyxml's interface

.merlin, _oasis, implem/META, myocamlbuild.ml, ppx/.merlin, ppx/_tags, ppx/ppx_reflect.ml, ppx/ppx_tyxml.ml, ppx/ppx_tyxml.mli, ppx/ppx_tyxml_ex.ml, ppx/ppx_tyxml_register.ml, ppx/ppx_tyxml_standalone.ml, tyxml-ppx.opam, tyxml.opam
@aantron, @let-def : I wouldn't mind a review there. :)
=> Use omp and driverify

ppx/META, tyxml-ppx.install
Preparing for a proper package split.
=> Add an independent tyxml-ppx ocamlfind package.

.travis.yml, ppx/common.ml, ppx/tyxml_ppx.ml, tools/tyxml_name.ml, tyxml-ppx.opam, tyxml.opam
This partially reverts 36ae0cafc6554485eafd315632f7f8550c2a06f9.
=> Support OCaml 4.02 again

docs/manual-wiki/functors.wiki, implem/tyxml_xml.ml, implem/tyxml_xml.mli, lib/html_f.ml, lib/html_sigs.mli, lib/html_types.mli, lib/svg_f.ml, lib/svg_sigs.mli, lib/xml_sigs.mli, ppx/reflect/reflect.ml, test/test_ppx.ml
This adds support for the following events:
- `ontouchstart`
- `ontouchend`
- `ontouchmove`
- `ontouchcancel`
=> Adding support for touch events

dune-project
Needed for me to `opam install .`
=> Add (name tyxml) to dune-project

lib/html_f.ml, lib/html_sigs.mli, lib/html_types.mli, test/test_html.ml
Fixes #280.
https://html.spec.whatwg.org/#the-translate-attribute
=> Add `translate` attribute

CHANGES.md, lib/html_f.ml, lib/html_sigs.mli, lib/html_types.mli, test/test_html.ml, test/test_ppx.ml, test/tyxml_test.ml
Also added `a_onclose` attribute https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onclose
=> Added dialog HTML element
